version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  ws-core:
    type: boolean
    default: false

  ws-react-client:
    type: boolean
    default: false

  ws-socket-server:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:16.11.0

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh
  
  build:
    parameters:
      package_name:
        type: string
    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install --immutable
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run: yarn lint
      - run:
          name: Start Test
          command: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.
  ws-core:
    when:  << pipeline.parameters.ws-core >>
    jobs:
      - build:
          name: ws-core-build
          package_name: ws-core

  ws-react-client:
    when:  << pipeline.parameters.ws-react-client >>
    jobs:
      - build:
          name: ws-react-client-build
          package_name: ws-react-client

  ws-socket-server:
    when: << pipeline.parameters.ws-socket-server >>
    jobs:
      - build:
          name: ws-socket-server-build
          package_name: ws-socket-server