name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Create .npmrc
        run: cat .npmrc

      - name: Populate .npmrc
        run: |
          echo "registry=https://registry.yarnpkg.com/" > .npmrc
          echo "@chumnend:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          title: Bump Package Versions
          commit: bumped package versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
